const translations = {
  de: {
    appName: 'PDF Studio',
    topline: 'Lokal im Browser · keine Uploads',
    title: 'Ein großes PDF aus allem.',
    subtitle: 'Ziehe Bilder und PDFs hinein, sieh die Vorschau, sortiere sie frei und lade alles als eine saubere PDF-Datei herunter.',
    clear: 'Leeren',
    uploadTitle: 'Dateien hier hineinziehen',
    uploadText: 'Oder klicken zum Auswählen. PDF, DOC, DOCX, TXT, RTF, ODT, PPTX, XLSX, PNG, JPG, JPEG und WebP werden unterstützt.',
    pdfNameLabel: 'PDF Name',
    pdfNamePlaceholder: 'Hier Namen eingeben z.B. Meine-Datei',
    ready: 'Bereit.',
    create: 'PDF herunterladen',
    files: 'Reihenfolge & Vorschau',
    sortHint: 'Zahl oben rechts ziehen oder unten eine Position eingeben. X löscht eine Datei.',
    noFiles: 'Noch keine Dateien ausgewählt. Ziehe Dateien oben hinein.',
    count: n => `${n} Datei${n === 1 ? '' : 'en'}`,
    chooseFirst: 'Bitte zuerst Dateien auswählen.',
    creating: 'PDF wird erstellt ...',
    done: 'Fertig! PDF wurde heruntergeladen.',
    error: 'Fehler beim Erstellen des PDFs.',
    remove: 'Entfernen',
    share: 'PDF teilen',
    shareUnsupported: 'Teilen wird von diesem Browser nicht unterstützt.',
    pdfPreview: 'PDF-Seite 1',
    imagePreview: 'Bildvorschau',
    docPreview: 'Dokument-Vorschau'
  },

  en: {
    appName: 'PDF Studio',
    topline: 'Local in your browser · no uploads',
    title: 'One big PDF from everything.',
    subtitle: 'Drop images and PDFs, see previews, arrange freely, and download one clean PDF file.',
    clear: 'Clear',
    uploadTitle: 'Drop files here',
    uploadText: 'Or click to select. PDF, DOC, DOCX, TXT, RTF, ODT, PPTX, XLSX, PNG, JPG, JPEG and WebP are supported.',
    pdfNameLabel: 'PDF name',
    pdfNamePlaceholder: 'Enter name here e.g. My-File',
    ready: 'Ready.',
    create: 'Download PDF',
    files: 'Order & Preview',
    sortHint: 'Drag the number in the top-right corner or enter a position below. X removes a file.',
    noFiles: 'No files selected yet. Drop files above.',
    count: n => `${n} file${n === 1 ? '' : 's'}`,
    chooseFirst: 'Please select files first.',
    creating: 'Creating PDF ...',
    done: 'Done! PDF was downloaded.',
    error: 'Error while creating the PDF.',
    remove: 'Remove',
    share: 'Share PDF',
    shareUnsupported: 'Sharing is not supported by this browser.',
    pdfPreview: 'PDF page 1',
    imagePreview: 'Image preview',
    docPreview: 'Document preview'
  },

  fr: {
    appName: 'PDF Studio',
    topline: 'Local dans le navigateur · aucun téléversement',
    title: 'Un grand PDF à partir de tout.',
    subtitle: 'Déposez des images et des PDF, prévisualisez-les, organisez-les librement et téléchargez un seul fichier PDF propre.',
    clear: 'Effacer',
    uploadTitle: 'Déposez les fichiers ici',
    uploadText: 'Ou cliquez pour sélectionner. PDF, DOC, DOCX, TXT, RTF, ODT, PPTX, XLSX, PNG, JPG, JPEG et WebP sont pris en charge.',
    pdfNameLabel: 'Nom du PDF',
    pdfNamePlaceholder: 'Entrez un nom, par ex. Mon-fichier',
    ready: 'Prêt.',
    create: 'Télécharger le PDF',
    files: 'Ordre & aperçu',
    sortHint: 'Faites glisser le numéro en haut à droite ou entrez une position ci-dessous. X supprime un fichier.',
    noFiles: 'Aucun fichier sélectionné. Déposez des fichiers ci-dessus.',
    count: n => `${n} fichier${n === 1 ? '' : 's'}`,
    chooseFirst: 'Veuillez d’abord sélectionner des fichiers.',
    creating: 'Création du PDF ...',
    done: 'Terminé ! Le PDF a été téléchargé.',
    error: 'Erreur lors de la création du PDF.',
    remove: 'Supprimer',
    share: 'Partager le PDF',
    shareUnsupported: 'Le partage n’est pas pris en charge par ce navigateur.',
    pdfPreview: 'Page PDF 1',
    imagePreview: 'Aperçu de l’image',
    docPreview: 'Aperçu du document'
  },

  it: {
    appName: 'PDF Studio',
    topline: 'Locale nel browser · nessun caricamento',
    title: 'Un grande PDF da tutto.',
    subtitle: 'Trascina immagini e PDF, visualizza l’anteprima, ordina liberamente e scarica un unico file PDF pulito.',
    clear: 'Svuota',
    uploadTitle: 'Trascina qui i file',
    uploadText: 'Oppure clicca per selezionare. Sono supportati PDF, DOC, DOCX, TXT, RTF, ODT, PPTX, XLSX, PNG, JPG, JPEG e WebP.',
    pdfNameLabel: 'Nome PDF',
    pdfNamePlaceholder: 'Inserisci un nome, es. Il-mio-file',
    ready: 'Pronto.',
    create: 'Scarica PDF',
    files: 'Ordine & anteprima',
    sortHint: 'Trascina il numero in alto a destra o inserisci una posizione sotto. X elimina un file.',
    noFiles: 'Nessun file selezionato. Trascina i file sopra.',
    count: n => `${n} file`,
    chooseFirst: 'Seleziona prima i file.',
    creating: 'Creazione PDF ...',
    done: 'Fatto! Il PDF è stato scaricato.',
    error: 'Errore durante la creazione del PDF.',
    remove: 'Rimuovi',
    share: 'Condividi PDF',
    shareUnsupported: 'La condivisione non è supportata da questo browser.',
    pdfPreview: 'Pagina PDF 1',
    imagePreview: 'Anteprima immagine',
    docPreview: 'Anteprima documento'
  },

  es: {
    appName: 'PDF Studio',
    topline: 'Local en el navegador · sin subidas',
    title: 'Un gran PDF a partir de todo.',
    subtitle: 'Arrastra imágenes y PDF, mira la vista previa, ordénalos libremente y descarga un único archivo PDF limpio.',
    clear: 'Limpiar',
    uploadTitle: 'Arrastra archivos aquí',
    uploadText: 'O haz clic para seleccionar. Se admiten PDF, DOC, DOCX, TXT, RTF, ODT, PPTX, XLSX, PNG, JPG, JPEG y WebP.',
    pdfNameLabel: 'Nombre del PDF',
    pdfNamePlaceholder: 'Introduce un nombre, p. ej. Mi-archivo',
    ready: 'Listo.',
    create: 'Descargar PDF',
    files: 'Orden & vista previa',
    sortHint: 'Arrastra el número de arriba a la derecha o introduce una posición abajo. X elimina un archivo.',
    noFiles: 'Aún no hay archivos seleccionados. Arrastra archivos arriba.',
    count: n => `${n} archivo${n === 1 ? '' : 's'}`,
    chooseFirst: 'Selecciona archivos primero.',
    creating: 'Creando PDF ...',
    done: '¡Listo! El PDF se ha descargado.',
    error: 'Error al crear el PDF.',
    remove: 'Eliminar',
    share: 'Compartir PDF',
    shareUnsupported: 'Este navegador no admite compartir.',
    pdfPreview: 'Página PDF 1',
    imagePreview: 'Vista previa de imagen',
    docPreview: 'Vista previa de documento'
  }
};
